steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--network=cloudbuild'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL'
      - '-t'
      - '$_GCR_HOSTNAME/$_PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_GCR_HOSTNAME/$_PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '$_SERVICE_NAME'
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$_PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'

options:
  machineType: 'E2_HIGHCPU_8' # Give it plenty of RAM/CPU for the Next.js build
